# -*- coding: utf-8 -*-
"""Tugas1_1301201590.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jqTL9DzsUGUr3PuM05ReHUh-VQDOzrkp
"""

import pandas as pd

df = pd.read_excel("/content/1615_phone_gyro.xlsx")
df.head()

import numpy as np
from scipy import signal

n_samples = 1000
t = np.linspace(0, 10, n_samples, endpoint=False)
sig = np.sin(2 * np.pi * 5 * t) + np.sin(2 * np.pi * 10 * t) + 0.5 * np.random.randn(n_samples)

fc = 4  # Cutoff frequency
fs = 100  # Sampling rate
order = 4  # Filter order
b, a = signal.butter(order, fc / (fs / 2), 'lowpass')

filtered_sig = signal.filtfilt(b, a, sig)

import matplotlib.pyplot as plt

plt.plot(t, sig, label='Original signal')
plt.plot(t, filtered_sig, label='Filtered signal')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.show()

import matplotlib.pyplot as plt

n = 1000
x = np.linspace(0, 10, n)
y = np.sin(x) + 0.1 * np.random.randn(n)
window_size = 15

def moving_average_filter(data, window_size):
    window = np.ones(window_size) / window_size
    return np.convolve(data, window, mode='valid')

y_filtered = moving_average_filter(y, window_size)

plt.plot(x, y, label='Original Signal')
plt.plot(x[window_size-1:], y_filtered, label='Moving Average Filtered Signal')
plt.xlabel('Time')
plt.ylabel('Amplitude')
plt.legend()
plt.show()